import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords:['about', 'course'] 
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <header>
        <nav className="flex  gap-2 bg-amber-400">
          <Link href='/'>Home</Link>
          <Link href='/abut'>About</Link>
        </nav>
      </header>
      <body className="min-h-full flex flex-col">{children}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
